### ISSUE TITLE
How to use it with vue-fontawesome ?

### ISSUE THREAD

**Issue by GreyXor** [userquin/vuetify-nuxt-module#12]
Hello, thank you for this module, it works well for me. I have a question about font-awesome.

[vue-fontawesome](https://github.com/FortAwesome/vue-fontawesome) brings a better render (SVG + JS) to display font-awesome icons, which are a definite advantage, how can it be used with this module?

**Comment by userquin** [comment]
@GreyXor working on it, stay tuned

**Comment by GreyXor** [comment]
Awesome! Thanks @userquin, vue-fontawesome provide a very nice way of using font-awesome font, let me know if you need any testing

**Comment by userquin** [comment]
@GreyXor sure, I don't use any font/svg icon on my projects, I use [UnoCSS Preset Icons](https://unocss.dev/presets/icons), once I'll send the PR, you can test it in the playground (just forking the branch)

**Comment by GreyXor** [comment]
Thanks! Will try ASAP

**Comment by GreyXor** [comment]
First I got these error when I `pnpm add github:userquin/vuetify-nuxt-module#userquin/feat-add-icons-support`

```bash
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /tmp/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
../.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1 [vuetify-nuxt-module@0.1.0]: Running pnpm-install script, done in 3.9s
../.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1 [vuetify-nuxt-module@0.1.0]: Running prepublishOnly script, failed in 7.5s
...8183_ccbeec8cf68352500b6f39669049c5a1 prepublishOnly$ pnpm build
│ > vuetify-nuxt-module@0.1.0 build /tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1
│ > pnpm dev:prepare && nuxt-module-build
│ > vuetify-nuxt-module@0.1.0 dev:prepare /tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1
│ > nuxt-module-build --stub && nuxi prepare playground
│ ℹ Stubbing vuetify-nuxt-module
│ Nuxi 3.6.2
│ ✔ Types generated in playground/.nuxt
│ ℹ Building vuetify-nuxt-module
│ src/module.ts(152,9): error TS2345: Argument of type 'VOptions' is not assignable to parameter of type 'VuetifyOptions'.
│   Types of property 'date' are incompatible.
│     Type 'DateOptions | undefined' is not assignable to type 'Partial<InternalDateOptions<any>> | undefined'.
│       Type 'DateOptions' is not assignable to type 'Partial<InternalDateOptions<any>>'.
│         Types of property 'adapter' are incompatible.
│           Type 'DateAdapter | undefined' is not assignable to type '(new (options: { locale: any; }) => DateInstance<any>) | DateInstance<any> | undefined'.
│             Type '"vuetify"' is not assignable to type '(new (options: { locale: any; }) => DateInstance<any>) | DateInstance<any> | undefined'.
│ Error [RollupError]: Failed to compile. Check the logs above.
│     at error (file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup@3.25.3/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
│     at Object.error (file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup@3.25.3/node_modules/rollup/dist/es/shared/node-entry.js:25119:20)
│     at Object.error (file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup@3.25.3/node_modules/rollup/dist/es/shared/node-entry.js:24247:42)
│     at generateDtsFromTs (file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.25.3_typescript@5.1.6/node_modules/rollup-plugin-dts/dis
│     at Object.transform (file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup-plugin-dts@5.3.0_rollup@3.25.3_typescript@5.1.6/node_modules/rollup-plugin-dts/dist
│     at file:///tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/node_modules/.pnpm/rollup@3.25.3/node_modules/rollup/dist/es/shared/node-entry.js:25312:40
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
│   id: '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/module.ts',
│   hook: 'resolveId',
│   code: 'PLUGIN_ERROR',
│   plugin: 'commonjs--resolver',
│   watchFiles: [
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/module.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/vite/vuetify-styles-plugin.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/types.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/vite/constants.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/vite/vuetify-configuration-plugin.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/vite/vuetify-date-configuration-plugin.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/utils/icons.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/vite/vuetify-icons-configuration-plugin.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/date.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/vuetify-date.mts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/utils/index.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/i18n.ts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/vuetify-i18n.mts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/vuetify-icons.mts',
│     '/tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1/src/runtime/plugins/vuetify.mts'
│   ]
│ }
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 7.5s at /tmp/.pnpm-store/v3/tmp/_tmp_38183_ccbeec8cf68352500b6f39669049c5a1
Packages: +187
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERR_PNPM_PREPARE_PACKAGE  Failed to prepare git-hosted package fetched from "https://codeload.github.com/userquin/vuetify-nuxt-module/tar.gz/6b5e81cc1517e9674731cfc7863c19336888d0da": vuetify-nuxt-module@0.1.0 prepublishOnly: `pnpm build`
Exit status 1
Progress: resolved 209, reused 186, downloaded 0, added 0
```

**Comment by userquin** [comment]
I'm fixing some bugs in i18n module, I have something working in my local, I'll try to finish it tmr.

Is is better to clone this repo in your local and then checkout the branch, then run `pnpm install && nr build && pnpm pack`, then copy tgz file and paste in your root folder and run `pnpm asd -D ./vietify....tgz` , to uninstall it `pnpm remove -D vuetify-nuxt-mpdule`, dont remove the tgz before uninstalling the dependency.

**Comment by userquin** [comment]
@GreyXor you can also work in the branch directly

About fa-svg, I'll include only the free icons version, later we can check more collections: I don't use any (fonts and svg icons) and we'll have some problems with vuetify components and v-icon using aliases, the page loads before the plugin and we'll need to hack SSR via `hydrated` (Nuxt problem that requires to fix it in the target app).

You can check my last commit in the PR, go to nuxt config and comment out the icons entry using `mdi-svg` (`@mdi/js`).

**Comment by userquin** [comment]
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/02a0c316-0b69-4513-8499-66160acd77ad)

**Comment by userquin** [comment]
ok, it seems to be working, testing some icons and I'll push changes:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/b34619e5-3dd0-4d21-8a05-9e4b4b77c99c)

**Comment by userquin** [comment]
I need to change `src/runtime/vuetify.ts` plugin
