### ISSUE TITLE
useRequestEvent is not defined

### ISSUE THREAD

**Issue by kingyue737** [userquin/vuetify-nuxt-module#139]
I want to play `vuetify-nuxt-module` on stackblitz but upgrading from `0.5.16` to `>=0.6.0` resulting into following error:

```
[nuxt] [request error] [unhandled] [500] useRequestEvent is not defined
  at callback (./node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-client-hints.server.mjs:200:19)  
  at _function (./node_modules/hookable/dist/index.mjs:153:14)  
  at eval (./node_modules/nuxt/dist/app/nuxt.js:66:44)  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:163:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:87:55)  
  at eval (./node_modules/nuxt/dist/app/nuxt.js:165:56)  
  at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3863:18)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:165:24)  
  at eval (./node_modules/nuxt/dist/app/nuxt.js:35:54)  
  at EffectScope.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:42:16)
```

https://stackblitz.com/edit/github-fi3r47-kvgvij

Not sure what breaking change is introduced in 0.6.0

**Comment by userquin** [comment]
@kingyue737 can you try with v0.6.4 (publishing to v0.6.3 failed)?
