### ISSUE TITLE
@font-face SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by SkyLissh** [userquin/vuetify-nuxt-module#146]
I get the following error when vuetify module is listed on my module list in `defineNuxtConfig` if I remove it everything runs fine.

```ERROR  Cannot restart nuxt:  Invalid or unexpected token                                                                               7:49:21 PM  

  @font-face {
  ^

  SyntaxError: Invalid or unexpected token
  at internalCompileFunction (node:internal/vm:73:18)
  at wrapSafe (node:internal/modules/cjs/loader:1153:20)
  at Module._compile (node:internal/modules/cjs/loader:1205:27)
  at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
  at Module.load (node:internal/modules/cjs/loader:1091:32)
  at Module._load (node:internal/modules/cjs/loader:938:12)
  at Module.require (node:internal/modules/cjs/loader:1115:19)
  at require (node:internal/modules/helpers:130:18)
  at jiti (node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:254014)
  at C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/vuetify.config.ts:1:163
  at evalModule (node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:256443)
  at jiti (node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:254371)
  at loadConfigFile (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/unconfig@0.3.11/node_modules/unconfig/dist/index.mjs:153:13)
  at async Object.load (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/unconfig@0.3.11/node_modules/unconfig/dist/index.mjs:76:24)
  at async loadVuetifyConfiguration (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/vuetify-nuxt-module@0.6.5_typescript@5.2.2_vite@4.5.0_vue@3.3.7/node_modules/vuetify-nuxt-module/dist/module.mjs:74:18)
  at async mergeVuetifyModules (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/vuetify-nuxt-module@0.6.5_typescript@5.2.2_vite@4.5.0_vue@3.3.7/node_modules/vuetify-nuxt-module/dist/module.mjs:103:27)
  at async load (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/vuetify-nuxt-module@0.6.5_typescript@5.2.2_vite@4.5.0_vue@3.3.7/node_modules/vuetify-nuxt-module/dist/module.mjs:405:7)
  at async setup (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/vuetify-nuxt-module@0.6.5_typescript@5.2.2_vite@4.5.0_vue@3.3.7/node_modules/vuetify-nuxt-module/dist/module.mjs:1368:5)
  at async normalizedModule (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/@nuxt+kit@3.8.1/node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/@nuxt+kit@3.8.0/node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/nuxt@3.8.0_sass@1.69.5_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.22/node_modules/nuxt/dist/index.mjs:3655:7)
  at async NuxtDevServer._load (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/nuxi@3.9.1/node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/nuxi@3.9.1/node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async _applyPromised (/C:/Users/aliss/Documents/Development/PaoMinis/pao-minis-web/node_modules/.pnpm/nuxi@3.9.1/node_modules/nuxi/dist/chunks/dev2.mjs:107:10)```

**Comment by safegergis** [comment]
Did you come up for a solution here? I am struggling with the same issue
