### ISSUE TITLE
Failed to resolve import

### ISSUE THREAD

**Issue by mubaidr** [userquin/vuetify-nuxt-module#158]
- Operating System: Windows_NT
- Node Version:     v21.1.0
- Nuxt Version:     3.8.2-28325498.bb533f8d
- CLI Version:      3.9.2-1699365944.a40650d
- Nitro Version:    2.8.0-28330337.786d3f8
- Package Manager:  pnpm@8.10.3
- Builder:          -
- User Config:      runtimeConfig, ssr, telemetry, imports, app, modules, devtools, pinia, vueuse, lodash, vuetify, vite, build, postcss, typescript, vue, experimental, nitro, router, routeRules
- Runtime Modules:  @nuxt/devtools@1.0.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.6.1, nuxt-lodash@2.5.3, vuetify-nuxt-module@0.6.7
- Build Modules:    -

```bash
 ERROR  Internal server error: Failed to resolve import "vuetify/lib/components/VSkeletonLoader/index.mjs" from "components\user\ApplicationSummary.vue". Does the file exist?  9:23:03 AM
  Plugin: vite:import-analysis
  File: E:/abcde-beta/application/components/user/ApplicationSummary.vue:95:64
  93 |  /* Vuetify */
  94 |  import { VChip as _component_v_chip } from "vuetify/lib/components/VChip/index.mjs"
  95 |  import { VSkeletonLoader as _component_VSkeletonLoader } from "vuetify/lib/components/VSkeletonLoader/index.mjs"
     |                                                                 ^
  96 |
  97 |
      at formatError (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
      at TransformContext.error (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
      at normalizeUrl (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41844:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
      at async Promise.all (index 7)
      at async TransformContext.transform (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41914:13)
      at async file:///E:/abcde-beta/application/node_modules/.pnpm/vite-plugin-inspect@0.7.41_@nuxt+kit@3.8.1_vite@4.5.0/node_modules/vite-plugin-inspect/dist/index.mjs:372:17
      at async Object.transform (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:30)
      at async loadAndTransform (file:///E:/abcde-beta/application/node_modules/.pnpm/vite@4.5.0_sass-embedded@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)


 ERROR  Failed to resolve import "vuetify/lib/components/VSkeletonLoader/index.mjs" from "components\user\ApplicationSummary.vue". Does the file exist?
```

**Comment by mubaidr** [comment]
Looks like this happens with Nuxt 3.8.1 and there is alreayd an open pull request/ update in progres for that here: https://github.com/userquin/vuetify-nuxt-module/pull/156

closing
