### ISSUE TITLE
[Layers] Error while requiring module `vuetify-nuxt-module`

### ISSUE THREAD

**Issue by Nura-21** [userquin/vuetify-nuxt-module#68]
Using with layers. When trying to generate, throws such error.

```
$ yarn install
yarn install v1.22.18
[1/4] Resolving packages...
success Already up-to-date.
$ nuxt prepare
[log] Nuxi 3.6.2
[info] [nuxt:tailwindcss] Using default Tailwind CSS file
[error] Error while requiring module `vuetify-nuxt-module`: Error: Cannot find module 'C:\GitLab-Runner-Front\builds\L34TKzhT\0\dit\front-vue\efo\efo\node_modules\vuetify-nuxt-module\node_modules\@nuxt\kit\dist\index.mjs'
[error] Cannot find module 'C:\GitLab-Runner-Front\builds\L34TKzhT\0\dit\front-vue\efo\efo\node_modules\vuetify-nuxt-module\node_modules\@nuxt\kit\dist\index.mjs'
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
  at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
  at resolveExports (node:internal/modules/cjs/loader:567:14)
  at Module._findPath (node:internal/modules/cjs/loader:636:[31](https://gitlab.halyklife.nb/dit/front-vue/efo/-/jobs/10972#L31))
  at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at _resolve (node_modules\jiti\dist\jiti.js:1:250100)
  at jiti (node_modules\jiti\dist\jiti.js:1:252409)
  at C:/GitLab-Runner-Front/builds/L[34](https://gitlab.halyklife.nb/dit/front-vue/efo/-/jobs/10972#L34)TKzhT/0/dit/front-vue/efo/efo/node_modules/vuetify-nuxt-module/dist/module.mjs:1:174
  at evalModule (node_modules\jiti\dist\jiti.js:1:255106)
error Command failed with exit code 1.
```

Any ideas?

**Comment by Nura-21** [comment]
I have core project with such package.json
```
{
  "name": "hl-core",
  "version": "0.0.9-beta.11",
  "license": "MIT",
  "private": false,
  "main": "nuxt.config.ts",
  "files": [
    "api/",
    "store/",
    "layouts/",
    "locales/",
    "configs/",
    "composables/",
    "components/",
    "plugins/",
    "pages/",
    "types/",
    "nuxt.config.ts",
    "tailwind.config.js",
    ".prettierrc"
  ],
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "typecheck": "nuxt typecheck"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.4.5",
    "@vueuse/components": "^10.2.1",
    "@vueuse/core": "^10.2.1",
    "@vueuse/nuxt": "^10.2.1",
    "nuxt": "^3.6.2",
    "prettier": "^2.8.8"
  },
  "dependencies": {
    "@intlify/unplugin-vue-i18n": "^0.12.2",
    "@mdi/font": "^7.2.96",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.4.11",
    "@vuepic/vue-datepicker": "^5.3.0",
    "animate.css": "^4.1.1",
    "axios": "^1.4.0",
    "fast-xml-parser": "4.0.12",
    "jwt-decode": "^3.1.2",
    "maska": "1.5.0",
    "pinia": "^2.1.4",
    "typedoc": "^0.24.8",
    "typescript": "5.0.4",
    "vue-i18n": "^9.2.2",
    "vue-json-pretty": "^2.2.4",
    "vue-toastification": "^2.0.0-rc.5",
    "vue-uuid": "^3.0.0",
    "vuetify-nuxt-module": "^0.5.3"
  }
}

```

Added 'vuetify-nuxt-module' to nuxt.config modules of core project.

package.json of child project.
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --dotenv .env.development",
    "test": "nuxt dev --dotenv .env.test",
    "prod": "nuxt dev --dotenv .env.production",
    "vercel": "nuxt dev --dotenv .env.vercel",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "typecheck": "nuxt typecheck"
  },
  "devDependencies": {
    "@nuxt/devtools": "^0.4.5",
    "@vueuse/nuxt": "^10.2.1",
    "nuxt": "^3.6.2",
    "prettier": "^2.8.8"
  },
  "dependencies": {
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.4",
    "vuetify-nuxt-module": "^0.5.3"
  }
}
```

In nuxt.config of child project.
```
extends: ['../core'],
modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss', '@vueuse/nuxt', 'vuetify-nuxt-module'],
```

**Comment by userquin** [comment]
can you check if peer dependencies installed? check if vuetify is installed, I use pnpm with `shamefully-hoist=true` in `.npmrc`

**Comment by Nura-21** [comment]
Also, should vuetify dependency doubled in `package.json`?

**Comment by userquin** [comment]
IIRC I bump nuxt to 3.6.5 yesterday...

**Comment by Nura-21** [comment]
Ok, I will try to update to 3.6.5

**Comment by Nura-21** [comment]
Is it okay that you have two versions of `@nuxt/kit` in your `package.json`
![image](https://github.com/userquin/vuetify-nuxt-module/assets/78026760/30307627-1add-491d-9f19-058fc0df4714)

**Comment by userquin** [comment]
I'm reviewing the dependencies...

**Comment by userquin** [comment]
@Nura-21 can you check with latest 0.5.5 version? I've tested it using pnpm and yarn creating a new nuxt project
