### ISSUE TITLE
Issue when trying to run with VueFirebase

### ISSUE THREAD

**Issue by subinznz** [userquin/vuetify-nuxt-module#88]
Hi 

I am getting the following error whenever I add 'vuetify-nuxt-module' with 'nuxt-vuefire'.

Without 'vuetify-nuxt-module'  my web application runs but soon as I add vuetify module I get the following errors : 

Any ideas ?

[nuxt] [request error] [unhandled] [500] Cannot find module './call-credentials'
Require stack:
- /com.docker.devenvironments.code/nuxt-vuetify/@grpc/grpc-js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)  
  at Module._load (node:internal/modules/cjs/loader:920:27)  
  at Module.require (node:internal/modules/cjs/loader:1141:19)  
  at require (node:internal/modules/cjs/helpers:110:18)  
  at ./@grpc/grpc-js:20:28  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:341:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:197:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:231:12)  
  at async ./@firebase/firestore:8:31

**Comment by TechAkayy** [comment]
@subinznz, try,

```
  build: {
    transpile: ['websocket'],
  },
```

**Comment by userquin** [comment]
@subinznz should be fixed with latest release v0.15.5

**Comment by subinznz** [comment]
Thanks man !! Legend 


Sent from Yahoo Mail for iPhone


On Wednesday, October 11, 2023, 6:59 pm, Joaquín Sánchez ***@***.***> wrote:




@subinznz should be fixed with latest release v0.15.5
